# Actividad 1: MODELOS DE LEGUAJE Y EXTRACCIÓN DE ENTIDADES
## Borja Lacalle Álvarez

In [2]:
#importar librerias necesarias para el desarrollo de la actividad de nlp
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import spacy
import nltk

In [3]:
# leer el archico hotel.csv dentro de la carpeta data
hotel = pd.read_csv('data/hotel.csv')
hotel

                                                  text  label
0    Es un gran hotel; el mejor de Asunción. Buenas...      3
1    hola. no suelo criticar jamas lo que paso pero...      3
2    Escogi meses antes de mi boda una habitacion p...      3
3    Voy a se Lo mas equitativo posible; porque soy...      3
4    Esta es una experiencia de septiembre de 2016;...      3
..                                                 ...    ...
195  Excelente atención; instalaciones; comodidad; ...      5
196  Realmente disfrutamos en pareja por 2 noches d...      5
197  Muy buena excelente; muy buena ubicación; cerc...      5
198  Pasé con mi familia la celebración del Año Nue...      5
199  La amabilidad de todo el personal (sin excepci...      5

[200 rows x 2 columns]

In [4]:
#normalizar los textos con la funcion normalize_document de mis_funciones.py
from mis_funciones import normalize_document
norm_hotel=[]

for document in hotel['text']:
    norm_hotel.append(normalize_document(document))

#ver solo los primeros 20 documentos normalizados
norm_hotel[:20]

['gran hotel mejor asunción buenas habitaciones gente maravillosa servicio excelente comida buena cargaron doble estadia expedia hotel hacer checkout llamar varias veces teléfono horas devolvieran dinero único malo gimnasio anuncian gimnasio solo pard caminadoras ojalá mejores equipos',
 'hola suelo criticar jamas paso vez animo hacerlo segunda estancia - mala experiencia - hotel primera probarlo cautivo concepto " ecologico " hotel segunda forzada tenia lugar alojarmeprimera cosa hotel supone ecologicamente sustentable puede descargar litros litros agua descarga ? asi " lluvia " supuestamente ?- puede tener tantos accesorios banio plastico absolutamente biodegrable menos cumple conceptos sustentabilidad tan buscados ultimamente ?- puede pagar u $ 600 suite presidencial salir ducha caminar metros mojados busqueda tesoro - llamese toallon - corriendo riesgo resvalarse hacer ultimo viaje ?- si atencion personalizada noche anterior habitcion simple previamete habia dicho podia mudar suite presidencial 12 mediodia parece interesante toquen timbre 10 11 diferentes personas diciendoles " puede mudar "- viajamos negocio primero buscamos ? creo buen escritorio conexion laptops cosas minimas tener toma corriente mismo lugar trabajo disparatado ? pues si habitacion barata tampoco " suite presidencial " - si ven carta " suite " tentadora descripcion cervezas frias esperan despues dia arduo ? feliz corre heladera saboreandola antemano oh sorpresa cerveza - ven dandose hermoso banio inmersion zas telefono suena habitacion salirse tina hacer busqueda gran tesoro - toallas - hotel mision ? seria si llamado avisarle gano loteria pasa si atiende cortan ? si hacen 3 veces mas termino 5 minutos ? quiero seguir solo ser honestos menos viajeros frecuentes tratamos balancear vida personal negocios',
 'escogi meses boda habitacion hacer sesion fotos 1 hora hotel viendo habitaciones finalmente escogi encanto pagué apenas pidieron pase hago check in dan ninguna explicacion lógica ningun gesto disculpas quedé decepcionada esperaba tipo atención',
 'voy mas equitativo posible persona bien intencionada encanto wilma señora adea habitación clasica persona sencillita predispuesta educada nota buen caracter humano principio primer llamado efectue atencion inmejorada',
 'experiencia septiembre 2016 asi quizas cosas cambiaronreservé senior suite luna miel organizadora paquete luna miel ( miembro hotel ) atenta ayudó amablemente comentado organizadora tenia nadie ayude poner flores auto iba llevar iglesia dia dijo preocupe personal iba ayudar ningun problemallegó dia boda preparé suite llamé recepción pedir ayuda flores auto recepcionista solo limitó decirme dejaron dicho podia hacer cuñadas bajar poner flores bueno mal entendidolo si molestó siguiente suegros quisieron regalar noche extra hotel llamaron sepamos hotel pidieron noche mas reservacion persona atendio dijo habiamos reservado noche extra ( verdad ) salimos hotel llegamos casa suegros preguntaron porqué quedamos si habiamos reservado noche mas terminaron llamando nuevo recepcion ( siempre hablamos misma recepcionista inconveniente ) suegra pregunto pasó supo responderle pasó peor recepcionista dijo habia comunicado intención noche extra parte suegros ciertoluego luna miel comenté via mail organizadora paquete luna miel inconveniente visto bueno dueña ofrecieron voucher almuerzo restaurante ir pasar recepción retirarlovamos hotel retirar voucher encuentra misma recepcionista problemas anteriores comento voucher solo limita decir dejaron dicho puede hacer solamente después mencioné contacté dueña hotel cambió actitud llamó organizadora dieron bendito voucher dos personasfuimos domingo almorzar llevamos voucher si piensan final feliz entramos dimos voucher almorzamos estabamos puerta salir alcanza corriendo personal diciendo voucher solo persona recepcionista solo marco voucher si novio mismas molestias final sentí alguien aprovechando situación debido bochorno hicieron pasar verificaron voucher sentemos mesadejo review atentos detalles hagan pasar situaciones incómodas',
 'entusiasmó idea alojarnos hotel solicitamos recepcionista muestre creemos idea representar misión franciscana representa frio habitaciones estilo antiguo acogedoras así restaurante aunque comida buena ambiente frio llama regresar especialmente alto costo',
 'argentinos trataron hacer lugar histórico embargo quedó frio caro acogedor recomiendo desayuno costo aparte carísimo mejor hub mismos argentinos menor precio buen servicio',
 'preparamos hotel si bien parece elegante comida buena personal amable ruido grupo personas llegaron parecía tan buenas condiciones buen sonido arpa costoso habitaciones servicio ofrecen',
 'molesto reciban dólares mundo recibien dese unidos demas países limítrofes perú bolivia brasil quisieron recibir dólares manifestaron firmas rayas',
 'segunda visita hotel misión presté atención puntos altos bajos comparando sendas experiencias : positivo shopping mariscal ampliando servicios tenés cines buenos 1 cuadra hotel así gastronomía villa morra lugar " chick " asunción aquí podés mover hacia lugares gran ciudad suma comodidad tenés medios transporte disposición impecable atención personal todas áreas ( front desk habitación ) puntos bajos falta estacionamiento cubierto carros ( quedan intemperie ) tampoco satisface cantidad habitaciones superficie destinada debiendo ubicarse peor casos calle próxima hotel servicio spa habilitado ( pesar publicitarlo hotel página web ) conste hablando hotel boutique compite precios hoteles 4 estrellas superiores general experiencia satisfactoria quedó sabor faltó',
 'lineas generales bien problemas check in ( habitacion aun disponible ) mañana limpieza cuartos apertura cierre puertas contiguas extremadamente ruidosa afecto descanso',
 'hotel categoria bidet ? bañera ? habitacion " amplia " digamoslo asi baño deja desearel desayuno rico surtido aunque parte dulce pobrela healderita habitacion bebidas temperatura ambiente apaga retirar llave hielo pedir traigan hielo pais hacen siempre 30 grados minima',
 'alojé hotel habitación standard pedí cuna hija 2 años hotel cómodo familias niños creo varias limitaciones : 1 ) bañera sólo ducha bañar bebé imposible 2 ) hotel rampa acceso discapacitados cochecitos bebés cada vez entraba salía empleado hotel ayudaba levantar coche bebé parecía incómodo3 ) piscina terraza climatizada agua congelada pude dejar hija bañe iba terminar enferma4 ) terraza además peligrosa niños unas barandas bajas dan vacio ecsaleras subir piscina mismo pude sacarle vista ningún momento hija tiempo miedo acerque barandas hotel creo lindo ir pareja chicos grandes cosas buenas hotel : 1 ) bien ubicado frente shopping 1 cuadra super 2 ) buena atención personal3 ) dan celulares gratis comuniques habitaciones ( grupo grande desencontramos ) 4 ) buen desayuno comida caro sé precios hoteles asunciónigual parece precio categpría hotel deberían tener instalaciones preparadas recibir niños discapacitados',
 'bueno ubicación decoración atención desayuno servicio limpieza atención critica : colchones duros mucha demora cocina almorzar comer desayuno perfecto',
 'comodo limpio inconveniente habitaciones planta baja subir escaleras tranquilo pesar lado ruta transitada desayuno completo variado atencion parte personal excelente estacionamiento pocos autos',
 'gimnasiomuy buen hotel solo desearía gimnasio mas equipado poder hacer deporte mantener ritmoterrazael servicio terraza debería disponible 23 hrs agradable temperatura horas noche',
 'volveria definitivamente bonito espacio cerca gran centro comercial comida buena trato altura camareras siempre atendieron llamado pedirles mas toallas bellboy atendio llamado instante hotel mas bien pequeño amenidades podrian hacer competir grandes cadenas',
 'costó conseguir lugar varias veces tratado conseguir lugar nunca podido habitación dieron 404 buena vista buena cama buena ducha bidé quedamos 5 noches general bien convenció pesar ser hotel boutique trataron forma impersonal sacando chicas tarde recepción siempre amables convenció atención desayuno bueno gracias muchacho toca excelente forma arpa cenamos varias veces restaurante comida buena atención tampoco excelente igualmente volveremos ir reservaremos tiempo espero conseguir mejor habitación mejor atención',
 'excelente servicio staff amable dispuesto hotel boutique lindo limpio bien ubicado lado muchas tiendas cafés restaurantes linda terraza techo piscina pequeña cómoda',
 'excelente amabilidad personal atiende rubros hotel ser destacado mas comentar hotel entiendo trip ad visor exige escribir 200 caracteres dar opinión deberían darse cuenta ustedes obligando hacer interesa escribir opinión limita di hotel ustedes sele ocurrió 200 caracteres']

In [11]:
#obtener matrices bow y tf-idf utilizando los 20 tokens mas frecuentes
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

#bow con los 20 tokens mas frecuentes
cv = CountVectorizer(max_features=20)
bow = cv.fit_transform(norm_hotel).toarray()

#imprima las matrices en pantalla de forma fácilmente legible
bow_df = pd.DataFrame(bow, columns=cv.get_feature_names_out())
bow_df

,asunción,atención,bien,buen,buena,bueno,calidad,desayuno,excelente,habitaciones,habitación,hotel,mas,mejor,personal,restaurante,servicio,si,siempre,ubicación
0,1,0,0,0,1,0,0,0,1,1,0,2,0,1,0,0,1,0,0,0
1,0,0,0,1,0,0,0,0,0,0,0,4,1,0,1,0,0,6,0,0
2,0,1,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0
3,0,0,1,1,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0
4,0,0,0,0,0,2,0,0,0,0,0,6,2,0,2,1,0,4,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,0,1,1,0,1,0,0,0,1,0,0,0,0,0,2,0,0,1,1,1
196,0,0,0,0,0,0,0,1,3,0,1,1,2,0,2,2,1,0,0,1
197,0,0,1,0,2,1,0,1,1,0,0,0,0,0,1,0,2,0,0,1
198,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,0
199,0,0,0,0,0,0,0,0,0,1,0,1,0,0,1,0,0,0,0,1

In [6]:
#tfidf con tfidfTransformer
from sklearn.feature_extraction.text import TfidfTransformer
tfidf = TfidfTransformer(norm='l2', use_idf=True, smooth_idf=True)
tfidf_matrix = tfidf.fit_transform(bow).toarray()
tfidf_df = pd.DataFrame(np.round(tfidf_matrix, 2), columns=cv.get_feature_names_out())
tfidf_df

,asunción,atención,bien,buen,buena,bueno,calidad,desayuno,excelente,habitaciones,habitación,hotel,mas,mejor,personal,restaurante,servicio,si,siempre,ubicación
0,0.44,0.00,0.00,0.00,0.33,0.00,0.00,0.00,0.29,0.33,0.00,0.43,0.00,0.45,0.00,0.00,0.33,0.00,0.00,0.00
1,0.00,0.00,0.00,0.12,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.28,0.14,0.00,0.09,0.00,0.00,0.94,0.00,0.00
2,0.00,0.67,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.63,0.00,0.40,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
3,0.00,0.00,0.41,0.47,0.00,0.00,0.00,0.00,0.00,0.00,0.54,0.00,0.56,0.00,0.00,0.00,0.00,0.00,0.00,0.00
4,0.00,0.00,0.00,0.00,0.00,0.32,0.00,0.00,0.00,0.00,0.00,0.47,0.32,0.00,0.21,0.16,0.00,0.69,0.16,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,0.00,0.31,0.29,0.00,0.29,0.00,0.00,0.00,0.25,0.00,0.00,0.00,0.00,0.00,0.50,0.00,0.00,0.42,0.38,0.34
196,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.16,0.48,0.00,0.24,0.12,0.49,0.00,0.32,0.50,0.19,0.00,0.00,0.22
197,0.00,0.00,0.26,0.00,0.53,0.35,0.00,0.23,0.23,0.00,0.00,0.00,0.00,0.00,0.23,0.00,0.53,0.00,0.00,0.31
198,0.00,0.00,0.00,0.00,0.00,0.00,0.66,0.00,0.00,0.00,0.00,0.32,0.00,0.00,0.00,0.68,0.00,0.00,0.00,0.00
199,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.53,0.00,0.34,0.00,0.00,0.46,0.00,0.00,0.00,0.00,0.62

In [7]:
#leer fichero esp.txt de la carpeta data
esp = pd.read_csv('data/esp.txt', sep='\t', header=None)
esp

                                                   0
0  El Hobbit es una novela de fantasía para niños...
1  El Hobbit está ambientado en la Tierra Media y...

In [8]:
from spacy import displacy

# Cargar el modelo de lenguaje en español
nlp_es = spacy.load('es_core_news_lg')

# Iterar sobre todas las noticias en el DataFrame
for index, row in esp.iterrows():
    texto_noticia = row[0]
    doc = nlp_es(texto_noticia)
    
    # Visualizar las entidades con displacy
    displacy.render(doc, style="ent", jupyter=True)

In [9]:
#leer fichero eng.txt de la carpeta data
eng = pd.read_csv('data/eng.txt', sep='\t', header=None)
eng

                                                   0
0  The Hobbit, or There and Back Again is a child...
1  The Hobbit is set in Middle-earth and follows ...

In [10]:
# Cargar el modelo de lenguaje en inglés
nlp_en = spacy.load('en_core_web_lg')
# Iterar sobre todas las noticias en el DataFrame
for index, row in eng.iterrows():
    texto_noticia = row[0]
    doc = nlp_en(texto_noticia)
    
    # Visualizar las entidades con displacy
    displacy.render(doc, style="ent", jupyter=True)

#### El modelo en inglés es más completo ya que tiene mejor clasificadas las entidades del texto. El modelo en español llama MISC (MISCELÁNEA) a muchas entidades probablemente porque es una traducción del inglés. Traducciones como Thorin Oakenshield a Thorin Escudo de Roble o el uso en inglés de la apóstrofe en Bilbo's journey hacen que el modelo en inglés coja a esos personajes como entidades person y no MISC. 

#### Además, el modelo inglés tiene las entidades de language, cardinal o date lo cual puede ser muy interesante para los análisis nlp que se pueden hacer en el mundo profesional

#### En un entorno profesional, se podría entrenar al modelo con ejemplos como que Thorin Escudo de Roble sea una persona, que Tierra Media sea un lugar y demás para ayudar al modelo en nuestro proyecto específico acerca de El Hobbit.

#### Hay que recordar que la mejora de los resultados es un proceso iterativo y depende en gran medida de la comprensión detallada de tu dominio y datos específicos. Experimentar con diferentes enfoques y observar cómo afectan la calidad de la extracción de entidades en tu caso particular es la clave.